name: Node Continuous Integration
on: push
jobs:
    build-node:
        name: Build and run node projects
        runs-on: ubuntu-latest
        container: node:18
        steps:
            - run: node --version
              name: Check node version
            - run: npm --version
              name: Check npm version
            - uses: actions/checkout@v4
              name: Checkout code from Github
            - run: npm install
              name: Install NPM packages
            - run: node app.js
              name: Run Node application